---

ntp_server: 192.168.100.144

syslog_server: 192.168.100.144

snmpv2_ro_community: public

tacacs_server: 192.168.100.144

email_contact: rado.mohyla@gmail.com

name_server: 192.168.100.144

clab-mgmt-network:
  - 172.20.20.0/24
lan-mgmt-network:
  - 192.168.100.0/24
